from presentation.gui.tabs.dashboard_tab import DashboardTab
from presentation.gui.tabs.operations_tab import OperationsTab
from presentation.gui.tabs.reports_tab import ReportsTab
from presentation.gui.tabs.budget_tab import BudgetTab
from presentation.gui.tabs.calendar_tab import CalendarTab
from presentation.gui.tabs.counterparty_tab import CounterpartyTab
from presentation.gui.tabs.forecast_tab import ForecastTab
from presentation.gui.tabs.settings_tab import SettingsTab
from presentation.gui.tabs.goals_tab import GoalsTab
from presentation.gui.tabs.scheduled_tab import ScheduledTab
from presentation.gui.tabs.search_tab import SearchTab
from presentation.gui.tabs.backup_tab import BackupTab
from presentation.gui.tabs.admin_tab import AdminTab